from pathlib import Path
from experiment_assets import Experiment

# --- Central, self-documenting registry ------------------------------------
# This replaces the "type 3 for experiment 3" problem: every experiment has
# a memorable name and a description right next to its file paths.

ARMS  = Path("models")
TRAJS = Path("trajectories")
RESUL = Path("results/arm_paths")
WTS   = Path("results/brain_weights")
GRAPH = Path("results/graphs")
VIDEO = Path("results/videos")

EXPERIMENTS: dict[str, Experiment] = {
    e.name: e
    for e in [
        Experiment(
            name="full_10",
            description="10kg mass manipulated over 1500 trials with no preset weights",
            trajectory=TRAJS / "traj_009.csv",
            actualArm=ARMS / "arm_3dofLargeMass.urdf",
            illusoryArm=ARMS / "arm_3dof.urdf",
            results=RESUL / "full_10.pkl",
            finalWts=WTS / "10kg_1500tr.npz",
            graphs=GRAPH / "full_10.png",
            videos=VIDEO / "full_10.mp4",
            nDof=3,
            nTrials=1500,
            load_weight_groups = (),
        ),
        Experiment(
            name="diff_traj",
            description="10kg mass manipulated over 1500 trials with no preset weights. Uses the same 8-figure shape trajectory but translated",
            trajectory=TRAJS / "traj_008.csv",
            actualArm=ARMS / "arm_3dofLargeMass.urdf",
            illusoryArm=ARMS / "arm_3dof.urdf",
            results=RESUL / "diff_traj.pkl",
            finalWts=WTS / "diff_traj.npz",
            graphs=GRAPH / "diff_traj.png",
            videos=VIDEO / "diff_traj.mp4",
            nDof=3,
            nTrials=1500,
            load_weight_groups = ()
        ),
        Experiment(
            name="test",
            description="test, only simulates one trial",
            trajectory=TRAJS / "traj_009.csv",
            actualArm=ARMS / "arm_3dofLargeMass.urdf",
            illusoryArm=ARMS / "arm_3dof.urdf",
            results=RESUL / "test.pkl",
            finalWts=WTS / "test.npz",
            graphs=GRAPH / "test.png",
            videos=VIDEO / "test.mp4",
            nDof=3,
            nTrials=1,
            load_weight_groups = ()
        ),
        Experiment(
            name="full_0",
            description="0kg mass manipulated over the full 1500 trials with no init weights",
            trajectory=TRAJS / "traj_009.csv",
            actualArm=ARMS / "arm_3dof.urdf",
            illusoryArm=ARMS / "arm_3dof.urdf",
            results=RESUL / "full_0.pkl",
            finalWts=WTS / "0kg.npz",
            graphs=GRAPH / "full_0.png",
            videos=VIDEO / "full_0.mp4",
            nDof=3,
            nTrials=1500,
            load_weight_groups = ()
        ),
        Experiment(
            name="full_1_5",
            description="1.5kg mass manipulated over the full 1500 trials with no init weights",
            trajectory=TRAJS / "traj_009.csv",
            actualArm=ARMS / "arm_3dofMedMass.urdf",
            illusoryArm=ARMS / "arm_3dof.urdf",
            results=RESUL / "full_1_5.pkl",
            finalWts=WTS / "1_5kg.npz",
            graphs=GRAPH / "full_1_5.png",
            videos=VIDEO / "full_1_5.mp4",
            nDof=3,
            nTrials=1500,
            load_weight_groups = ()
        ),
        Experiment(
            name="full_0_5",
            description="0.5kg mass manipulated over the full 1500 trials with no init weights",
            trajectory=TRAJS / "traj_009.csv",
            actualArm=ARMS / "arm_3dofSmallMass.urdf",
            illusoryArm=ARMS / "arm_3dof.urdf",
            results=RESUL / "full_0_5.pkl",
            finalWts=WTS / "0_5kg.npz",
            graphs=GRAPH / "full_0_5.png",
            videos=VIDEO / "full_0_5.mp4",
            nDof=3,
            nTrials=1500,
            load_weight_groups = (),
        ),
        Experiment(
            name="pf_pc_1_5",
            description="1.5kg mass manipulated over 150 trials with init weights for 1.5kg",
            trajectory=TRAJS / "traj_009.csv",
            actualArm=ARMS / "arm_3dofMedMass.urdf",
            illusoryArm=ARMS / "arm_3dof.urdf",
            results=RESUL / "pf_pc_1_5.pkl",
            finalWts=WTS / "pf_pc_1_5kg.npz",
            graphs=GRAPH / "pf_pc_1_5.png",
            videos=VIDEO / "pf_pc_1_5.mp4",
            nDof=3,
            nTrials=150,
            load_weight_groups = ('mf_dcn','pc_dcn'),
            initialWts=WTS / "1_5_final.npz",
            plastic   = ('pf_pc',),
        ),
        Experiment(
            name="pf_pc_10",
            description="1.5kg mass manipulated over 150 trials with init weights for 10kg",
            trajectory=TRAJS / "traj_009.csv",
            actualArm=ARMS / "arm_3dofMedMass.urdf",
            illusoryArm=ARMS / "arm_3dof.urdf",
            results=RESUL / "pf_pc_10.pkl",
            finalWts=WTS / "pf_pc_10kg.npz",
            graphs=GRAPH / "pf_pc_10.png",
            videos=VIDEO / "pf_pc_10.mp4",
            nDof=3,
            nTrials=150,
            load_weight_groups = ('mf_dcn','pc_dcn'),
            initialWts=WTS / "10_final.npz",
            plastic   = ('pf_pc',),
        ),
        Experiment(
            name="pf_pc_0_5",
            description="1.5kg mass manipulated over 150 trials with init weights for 0.5kg",
            trajectory=TRAJS / "traj_009.csv",
            actualArm=ARMS / "arm_3dofMedMass.urdf",
            illusoryArm=ARMS / "arm_3dof.urdf",
            results=RESUL / "pf_pc_0_5.pkl",
            finalWts=WTS / "pf_pc_0_5kg.npz",
            graphs=GRAPH / "pf_pc_0_5.png",
            videos=VIDEO / "pf_pc_0_5.mp4",
            nDof=3,
            nTrials=150,
            load_weight_groups = ('mf_dcn','pc_dcn'),
            initialWts=WTS / "0_5_final.npz",
            plastic   = ('pf_pc',),
        ),
        Experiment(
            name="pf_pc_only",
            description="10kg mass manipulated over 1500 trials, pf-pc initial for 0kg, other sites initial 10kg but not plastic.",
            trajectory=TRAJS / "traj_009.csv",
            actualArm=ARMS / "arm_3dofLargeMass.urdf",
            illusoryArm=ARMS / "arm_3dof.urdf",
            results=RESUL / "pf_pc_only.pkl",
            finalWts=WTS / "pf_pc_onlykg.npz",
            graphs=GRAPH / "pf_pc_only.png",
            videos=VIDEO / "pf_pc_only.mp4",
            nDof=3,
            nTrials=1500,
            load_weight_groups = ('mf_dcn', 'pc_dcn'),
            initialWts=WTS / "10_final.npz",
            defaultWts=WTS / "0_final.npz",
            plastic=('pf_pc')
        ),
        Experiment(
            name="no_pc_dcn",
            description="10kg mass manipulated over 1500 trials, pf-pc and mf-dcn initial for 0kg, pc-dcn initial 10kg but not plastic.",
            trajectory=TRAJS / "traj_009.csv",
            actualArm=ARMS / "arm_3dofLargeMass.urdf",
            illusoryArm=ARMS / "arm_3dof.urdf",
            results=RESUL / "no_pc_dcn.pkl",
            finalWts=WTS / "no_pc_dcn.npz",
            graphs=GRAPH / "no_pc_dcn.png",
            videos=VIDEO / "no_pc_dcn.mp4",
            nDof=3,
            nTrials=1500,
            load_weight_groups = ('pc_dcn',),
            initialWts=WTS / "10_final.npz",
            defaultWts=WTS / "0_final.npz",
            plastic=('pf_pc', 'mf_dcn')
        ),
        Experiment(
            name="no_mf_dcn",
            description="10kg mass manipulated over 1500 trials, pf-pc and pc-dcn initial for 0kg, mf-dcn initial 10kg but not plastic.",
            trajectory=TRAJS / "traj_009.csv",
            actualArm=ARMS / "arm_3dofLargeMass.urdf",
            illusoryArm=ARMS / "arm_3dof.urdf",
            results=RESUL / "no_mf_dcn.pkl",
            finalWts=WTS / "no_mf_dcn.npz",
            graphs=GRAPH / "no_mf_dcn.png",
            videos=VIDEO / "no_mf_dcn.mp4",
            nDof=3,
            nTrials=1500,
            load_weight_groups = ('mf_dcn',),
            initialWts=WTS / "10_final.npz",
            defaultWts=WTS / "0_final.npz",
            plastic=('pf_pc', 'pc_dcn')
        ),
        Experiment(
            name="all_plastic",
            description="10kg mass manipulated over 1500 trials with init weights for 0kg, all sites plastic",
            trajectory=TRAJS / "traj_009.csv",
            actualArm=ARMS / "arm_3dofLargeMass.urdf",
            illusoryArm=ARMS / "arm_3dof.urdf",
            results=RESUL / "no_mf_dcn.pkl",
            finalWts=WTS / "no_mf_dcn.npz",
            graphs=GRAPH / "all_plastic.png",
            videos=VIDEO / "all_plastic.mp4",
            nDof=3,
            nTrials=1500,
            load_weight_groups = ('pf_pc', 'pc_dcn', 'mf_dcn'),
            initialWts=WTS / "0_final.npz",
            plastic=('pf_pc', 'pc_dcn', 'mf_dcn')
        ),
        Experiment(
            name="calculate_0kg_weights",
            description="0kg mass manipulated over 10,000 trials, all sites plastic",
            trajectory=TRAJS / "traj_009.csv",
            actualArm=ARMS / "arm_3dof.urdf",
            illusoryArm=ARMS / "arm_3dof.urdf",
            results=RESUL / "0_final.pkl",
            finalWts=WTS / "0_final.npz",
            graphs=GRAPH / "calculate_0.png",
            videos=VIDEO / "calculate_0.mp4",
            nDof=3,
            nTrials=10000,
        ),
        Experiment(
            name="calculate_0_5kg_weights",
            description="0.5kg mass manipulated over 10,000 trials, all sites plastic",
            trajectory=TRAJS / "traj_009.csv",
            actualArm=ARMS / "arm_3dofSmallMass.urdf",
            illusoryArm=ARMS / "arm_3dof.urdf",
            results=RESUL / "0_5_final.pkl",
            finalWts=WTS / "0_5_final.npz",
            graphs=GRAPH / "calculate_0_5.png",
            videos=VIDEO / "calculate_0_5.mp4",
            nDof=3,
            nTrials=10000,
        ),
        Experiment(
            name="calculate_1_5kg_weights",
            description="1.5kg mass manipulated over 10,000 trials, all sites plastic",
            trajectory=TRAJS / "traj_009.csv",
            actualArm=ARMS / "arm_3dofMedMass.urdf",
            illusoryArm=ARMS / "arm_3dof.urdf",
            results=RESUL / "1_5_final.pkl",
            finalWts=WTS / "1_5_final.npz",
            graphs=GRAPH / "calculate_1_5.png",
            videos=VIDEO / "calculate_1_5.mp4",
            nDof=3,
            nTrials=10000,
        ),
        Experiment(
            name="calculate_10kg_weights",
            description="10kg mass manipulated over 10,000 trials, all sites plastic",
            trajectory=TRAJS / "traj_009.csv",
            actualArm=ARMS / "arm_3dofLargeMass.urdf",
            illusoryArm=ARMS / "arm_3dof.urdf",
            results=RESUL / "10_final.pkl",
            finalWts=WTS / "10_final.npz",
            graphs=GRAPH / "calculate_10.png",
            videos=VIDEO / "calculate_10.mp4",
            nDof=3,
            nTrials=10000,
        ),

    ]
}
